
version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n-local
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - ./data:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=Marian1976
      - N8N_BASIC_AUTH_PASSWORD=Juani2214
      - N8N_TUNNEL_SUBDOMAIN=marian-n8n